# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import dummy_pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'About US'), ('terms', 'Terms'), ('privacy', 'Privacy'), ('faq', 'FAQ'), ('delivery', 'Delivery'), ('exchange', 'Exchange')], default='about', max_length=2)),
                ('image', models.ImageField(upload_to=dummy_pages.models.image_upload_to)),
                ('desc', models.CharField(max_length=2000)),
            ],
        ),
    ]
