// fetch products actions
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

// filter products actions
export const FILTER_PRODUCTS_START = 'FILTER_PRODUCTS_START'
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS'
export const FILTER_PRODUCTS_FAIL = 'FILTER_PRODUCTS_FAIL'

// filter products actions
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL'

// filter products actions
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL'

// filter products actions
export const FETCH_CATEGORIE_START = 'FETCH_CATEGORIE_START'
export const FETCH_CATEGORIE_SUCCESS = 'FETCH_CATEGORIE_SUCCESS'
export const FETCH_CATEGORIE_FAIL = 'FETCH_CATEGORIE_FAIL'

// dummy pages actions
export const FETCH_DUMMY_PAGES_START = 'FETCH_DUMMY_PAGES_START'
export const FETCH_DUMMY_PAGES_SUCCESS = 'FETCH_DUMMY_PAGES_SUCCESS'
export const FETCH_DUMMY_PAGES_FAIL = 'FETCH_DUMMY_PAGES_FAIL'

// register user actions
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

// login user actions
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGOUT_USER = 'LOGOUT_USER'

// user profile actions
export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'

// wishlist actions
export const GET_WISHLIST_COUNT = 'GET_WISHLIST_COUNT'
export const GET_WISHLIST_ITEMS = 'GET_WISHLIST_ITEMS'
export const GET_WISHLIST_ID = 'GET_WISHLIST_ID'
export const DELETE_WISHLIST_ITEM = 'DELETE_WISHLIST_ITEM'
