export const AuthTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    USER_PROFILE: "USER_PROFILE"
};

export const ShopTypes = {
    PRODUCTS: "PRODUCTS",
    CATEGORIES: "CATEGORIES",
    SELLERS: "SELLERS",
    BRANDS: "BRANDS",
};
export const cartTypes= {
    SET_TO_CART:"SET_TO_CART",
    CHANGE_QUANTITY:"CHANGE_QUANTITY",
    CARTITEMS:"CARTITEMS"
}; 