# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.image_upload_to_featured)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Variation')),
            ],
        ),
    ]
