# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 01:43
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatured',
            name='text_css_color',
            field=colorful.fields.RGBColorField(default=0),
            preserve_default=False,
        ),
    ]
