# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productseller_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='seller_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller'),
            preserve_default=False,
        ),
    ]
