# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 01:22
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0003_auto_20180408_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='color',
            field=colorful.fields.RGBColorField(default=454654),
            preserve_default=False,
        ),
    ]
