# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 00:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_variation_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.ProductBrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller'),
            preserve_default=False,
        ),
    ]
