# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
