# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname',
        ),
    ]
